//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 07:04:00 PM CEST 
//


package rs.ac.uns.ftn.agenti;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.agenti package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.agenti
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateAccommodationRequest }
     * 
     */
    public CreateAccommodationRequest createCreateAccommodationRequest() {
        return new CreateAccommodationRequest();
    }

    /**
     * Create an instance of {@link AccommodationUnitWs }
     * 
     */
    public AccommodationUnitWs createAccommodationUnitWs() {
        return new AccommodationUnitWs();
    }

    /**
     * Create an instance of {@link Pricing }
     * 
     */
    public Pricing createPricing() {
        return new Pricing();
    }

    /**
     * Create an instance of {@link GetAccommodationByAgentIdResponse }
     * 
     */
    public GetAccommodationByAgentIdResponse createGetAccommodationByAgentIdResponse() {
        return new GetAccommodationByAgentIdResponse();
    }

    /**
     * Create an instance of {@link MessageWs }
     * 
     */
    public MessageWs createMessageWs() {
        return new MessageWs();
    }

    /**
     * Create an instance of {@link ReservationWs }
     * 
     */
    public ReservationWs createReservationWs() {
        return new ReservationWs();
    }

    /**
     * Create an instance of {@link SendMessageRequest }
     * 
     */
    public SendMessageRequest createSendMessageRequest() {
        return new SendMessageRequest();
    }

    /**
     * Create an instance of {@link MessagesResponse }
     * 
     */
    public MessagesResponse createMessagesResponse() {
        return new MessagesResponse();
    }

    /**
     * Create an instance of {@link BookIntervalRequest }
     * 
     */
    public BookIntervalRequest createBookIntervalRequest() {
        return new BookIntervalRequest();
    }

    /**
     * Create an instance of {@link LoginAgentResponse }
     * 
     */
    public LoginAgentResponse createLoginAgentResponse() {
        return new LoginAgentResponse();
    }

    /**
     * Create an instance of {@link LoginAgentRequest }
     * 
     */
    public LoginAgentRequest createLoginAgentRequest() {
        return new LoginAgentRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationParametersResponse }
     * 
     */
    public GetAccommodationParametersResponse createGetAccommodationParametersResponse() {
        return new GetAccommodationParametersResponse();
    }

    /**
     * Create an instance of {@link AdditionalServicesWs }
     * 
     */
    public AdditionalServicesWs createAdditionalServicesWs() {
        return new AdditionalServicesWs();
    }

    /**
     * Create an instance of {@link AccommodationCategoryWs }
     * 
     */
    public AccommodationCategoryWs createAccommodationCategoryWs() {
        return new AccommodationCategoryWs();
    }

    /**
     * Create an instance of {@link AccommodationTypeWs }
     * 
     */
    public AccommodationTypeWs createAccommodationTypeWs() {
        return new AccommodationTypeWs();
    }

    /**
     * Create an instance of {@link GetMessagesRequest }
     * 
     */
    public GetMessagesRequest createGetMessagesRequest() {
        return new GetMessagesRequest();
    }

    /**
     * Create an instance of {@link GetAccommodationByAgentIdReguest }
     * 
     */
    public GetAccommodationByAgentIdReguest createGetAccommodationByAgentIdReguest() {
        return new GetAccommodationByAgentIdReguest();
    }

    /**
     * Create an instance of {@link GetReservationsRequest }
     * 
     */
    public GetReservationsRequest createGetReservationsRequest() {
        return new GetReservationsRequest();
    }

    /**
     * Create an instance of {@link CreateAccommodationResponse }
     * 
     */
    public CreateAccommodationResponse createCreateAccommodationResponse() {
        return new CreateAccommodationResponse();
    }

    /**
     * Create an instance of {@link GetMessagesResponse }
     * 
     */
    public GetMessagesResponse createGetMessagesResponse() {
        return new GetMessagesResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationParametersRequest }
     * 
     */
    public GetAccommodationParametersRequest createGetAccommodationParametersRequest() {
        return new GetAccommodationParametersRequest();
    }

    /**
     * Create an instance of {@link BookIntervalResponse }
     * 
     */
    public BookIntervalResponse createBookIntervalResponse() {
        return new BookIntervalResponse();
    }

    /**
     * Create an instance of {@link AgentWs }
     * 
     */
    public AgentWs createAgentWs() {
        return new AgentWs();
    }

}
