//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.24 at 01:54:50 AM CEST 
//


package rs.ac.uns.ftn.agenti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pricing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pricing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="january" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="february" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="march" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="april" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="may" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="june" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="july" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="august" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="september" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="october" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="november" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="december" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pricing", propOrder = {
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december"
})
public class Pricing {

    protected int january;
    protected int february;
    protected int march;
    protected int april;
    protected int may;
    protected int june;
    protected int july;
    protected int august;
    protected int september;
    protected int october;
    protected int november;
    protected int december;

    /**
     * Gets the value of the january property.
     * 
     */
    public int getJanuary() {
        return january;
    }

    /**
     * Sets the value of the january property.
     * 
     */
    public void setJanuary(int value) {
        this.january = value;
    }

    /**
     * Gets the value of the february property.
     * 
     */
    public int getFebruary() {
        return february;
    }

    /**
     * Sets the value of the february property.
     * 
     */
    public void setFebruary(int value) {
        this.february = value;
    }

    /**
     * Gets the value of the march property.
     * 
     */
    public int getMarch() {
        return march;
    }

    /**
     * Sets the value of the march property.
     * 
     */
    public void setMarch(int value) {
        this.march = value;
    }

    /**
     * Gets the value of the april property.
     * 
     */
    public int getApril() {
        return april;
    }

    /**
     * Sets the value of the april property.
     * 
     */
    public void setApril(int value) {
        this.april = value;
    }

    /**
     * Gets the value of the may property.
     * 
     */
    public int getMay() {
        return may;
    }

    /**
     * Sets the value of the may property.
     * 
     */
    public void setMay(int value) {
        this.may = value;
    }

    /**
     * Gets the value of the june property.
     * 
     */
    public int getJune() {
        return june;
    }

    /**
     * Sets the value of the june property.
     * 
     */
    public void setJune(int value) {
        this.june = value;
    }

    /**
     * Gets the value of the july property.
     * 
     */
    public int getJuly() {
        return july;
    }

    /**
     * Sets the value of the july property.
     * 
     */
    public void setJuly(int value) {
        this.july = value;
    }

    /**
     * Gets the value of the august property.
     * 
     */
    public int getAugust() {
        return august;
    }

    /**
     * Sets the value of the august property.
     * 
     */
    public void setAugust(int value) {
        this.august = value;
    }

    /**
     * Gets the value of the september property.
     * 
     */
    public int getSeptember() {
        return september;
    }

    /**
     * Sets the value of the september property.
     * 
     */
    public void setSeptember(int value) {
        this.september = value;
    }

    /**
     * Gets the value of the october property.
     * 
     */
    public int getOctober() {
        return october;
    }

    /**
     * Sets the value of the october property.
     * 
     */
    public void setOctober(int value) {
        this.october = value;
    }

    /**
     * Gets the value of the november property.
     * 
     */
    public int getNovember() {
        return november;
    }

    /**
     * Sets the value of the november property.
     * 
     */
    public void setNovember(int value) {
        this.november = value;
    }

    /**
     * Gets the value of the december property.
     * 
     */
    public int getDecember() {
        return december;
    }

    /**
     * Sets the value of the december property.
     * 
     */
    public void setDecember(int value) {
        this.december = value;
    }

}
